### ISSUE TITLE
`E/launcher - BUG: launcher exited with 1 tasks remaining` when using mocha-multi

### ISSUE THREAD

**Issue by KrzysztofKowalskiKainos** [stanleyhlng/mocha-multi-reporters#23]
Issue appears when trying to use reporters: `mocha-junit-reporter` and `mocha-spectreport-reporter`. Changes proposed in https://github.com/stanleyhlng/mocha-multi-reporters/pull/22 fix this issue.

This issue causes non-zero return code even when all tests are green.

**Comment by stanleyhlng** [comment]
@KrzysztofKowalskiKainos  Thanks for reporting.  I am going to release a new version soon =) stay tuned.

**Comment by stanleyhlng** [comment]
published [mocha-multi-reporters@1.1.2]

[mocha-multi-reporters@1.1.2]: https://github.com/stanleyhlng/mocha-multi-reporters/releases/tag/v1.1.2
