### ISSUE TITLE
Support mochawesome

### ISSUE THREAD

**Issue by jmpresso** [stanleyhlng/mocha-multi-reporters#34]
**Issue**
The [mochawesome ](https://github.com/adamgruber/mochawesome)reporter does not appear to work with mocha-multi-reporters. mocha-multi-reporters appears to correctly register mochawesome with my custom options set in mochawesomeReporterOptions. However, it never writes the HTML report out at the end.

I used a configuration as follows, with grunt-mocha-test

            newReportNoFail: {
                options: {
                    reporter: 'mocha-multi-reporters',
                    reporterOptions: {
                        "reporterEnabled": "xunit,mochawesome",
                        "xunitReporterOptions": {
                            "output": "reports/tests/xunit.xml"
                        },
                        "mochawesomeReporterOptions": {
                            reportDir:'reports/tests/htmlreport',
                            reportFilename:'index',
                            reportTitle: "My Unit Tests",
                            reportPageTitle: "My Unit Tests",
                            inlineAssets: true,
                            overwrite: true
                        }
                    },
                    noFail: false
                },
                src: ['test/**/*.spec.js']
            },

**Additional Analysis**
It looks to me like at least one of the reasons is that mochawesome expects mocha to call it's "done" function, which is what writes mochawesomes report. See the "done" function at the bottom of this file in mocha.js- https://github.com/mochajs/mocha/blob/master/lib/mocha.js. 

Since the official reporter is mocha-multi-reporters, it attempts to call a done function there. Is it possible for a 'done' function to be added to mocha-multi-reporters, and propagate that call to the registered reporters? I'm not 100% certain this is the only issue, but looks to be at least one of them.

**Comment by lemonbutter** [comment]
Should be pretty easy to achieve this.
This little node module combines junit-reporter and mochawesome.

https://github.com/alaauco/mochawesome-junit-reporter/blob/master/index.js

**Comment by jmpresso** [comment]
Thanks, you're right. I'll make a fix for this and submit a PR.

**Comment by chris-goodchild** [comment]
@jmpresso - I uncovered the same issue today and have a fix ready to go into a PR tonight. Happy to hang on if you've already implemented a fix though? 😄

**Comment by jmpresso** [comment]
@chris-goodchild I coded up a quick fix but haven't tested it yet. Go ahead and submit yours- thanks!

**Comment by chris-goodchild** [comment]
@jmpresso / @lemonbutter - everything looks fine except for the outdated dependencies. I think that should be tackled in a separate PR though :)

**Comment by stanleyhlng** [comment]
merged and published published https://github.com/stanleyhlng/mocha-multi-reporters/releases/tag/v1.1.5

https://github.com/stanleyhlng/mocha-multi-reporters/pull/36
