### ISSUE TITLE
Missing (peer) dependency 'mocha'

### ISSUE THREAD

**Issue by mgroenhoff** [stanleyhlng/mocha-multi-reporters#50]
`lib/MultiReporters.js` requires `mocha` but package.json has `mocha` in it's `devDependencies` but it should be in `peerDependencies`.

I currently have an issue where mocha reports that it can not load mocha-multi-reporters:
```
"mocha-multi-reporters" reporter not found
      throw new Error('invalid reporter "' + reporter + '"');
      ^
Error: invalid reporter "mocha-multi-reporters"
```
However mocha DOES find the reporter but it fails to load because the reporter fails to require mocha in our case.

**Comment by stanleyhlng** [comment]
@mgroenhoff Thanks for reporting.  Can you create a PR to set `mocha` as `peerDependencies` instead of `devDependencies`? Thanks!
