### ISSUE TITLE
Out of date dependencies

### ISSUE THREAD

**Issue by matcha440** [stanleyhlng/mocha-multi-reporters#54]
I feel like for the use case I'm looking at, this is one of the more viable node modules out there, but there is a problem with the dependencies being out of date.  I'd ask if anyone will be looking into that, but looking at the commit history of this repo it seems nothing has been done here for almost a year.  Is this repo still being maintained?  @stanleyhlng ?

**Comment by stanleyhlng** [comment]
hi @matcha440 , thank you for the message.  i can spend sometimes to update the dependencies. stay tuned.

**Comment by matcha440** [comment]
@stanleyhlng awesome, thanks for the response!

**Comment by francisu** [comment]
Fixed in 1.5.1
