### ISSUE TITLE
Errors when using Mocha 6 + Cypress

### ISSUE THREAD

**Issue by michaelw85** [stanleyhlng/mocha-multi-reporters#56]
### Expected behavior
No errors

### Actual behavior
Errors when 2nd test suite is run. "Cannot read property xxxx of undefined"

### Information about the Issue
Using following packages:
```json
    "cypress": "^3.1.5",
    "mocha": "^6.0.0",
    "mocha-junit-reporter": "^1.18.0",
    "mocha-multi-reporters": "^1.1.7",
```

### Steps to reproduce the behavior
Follow [this guide](https://docs.cypress.io/guides/tooling/reporters.html#Multiple-Reporters) to setup mocha-multi-reporters in cypress and run a test setup with 2 separate test files using spec and junit reporter.

### Workaround ###
Downgrade to mocha 5.2.0 and everything is working as expected.

**Comment by YOU54F** [comment]
Just fixed this and proposed the following 2 PR's

https://github.com/stanleyhlng/mocha-multi-reporters/pull/58
https://github.com/michaelleeallen/mocha-junit-reporter/pull/80

My branch tracking the changes, with failing builds with mocha 6 pre and post fix is here

https://github.com/YOU54F/cypressio-docker-typescript/pull/15/files

If you do want to move up to mocha 6, you can pull my forked branch in the interim, whilst we wait for the maintainers of the source repo to review/merge/release the PR

```
    "mocha": "^6.0.0",
    "mocha-junit-reporter": "YOU54F/mocha-junit-reporter#master",
    "mocha-multi-reporters": "YOU54F/mocha-multi-reporters#master",
```

**Comment by YOU54F** [comment]
Updated instructions

I've now updated, tested and released updated modules that fix this with mocha 6, but also retains backwards compatibility with mocha 5 and earlier versions.

https://www.npmjs.com/package/cypress-multi-reporters
https://www.npmjs.com/package/mocha-junit-reporters

[Example against Mocha 5](https://github.com/YOU54F/cypress-docker-typescript/pull/32)
[Example against Mocha 6](https://github.com/YOU54F/cypress-docker-typescript/pull/22/)

the changes required are minimal 

`npm i mocha-junit-reporters`
`npm i cypress-multi-reporters`

in reporterOpts.json

```json
{
  "reporterEnabled": "mocha-junit-reporters, mochawesome",
  "mochaJunitReportersReporterOptions": {
    "mochaFile": "cypress/reports/junit/test_results[hash].xml",
    "toConsole": false
  },
  "mochawesomeReporterOptions": {
    "reportDir": "cypress/reports/mocha",
    "quiet": true,
    "overwrite": false,
    "html": false,
    "json": true
  }
} 
```

in cypress.json

```json
{
  ...
  "reporter": "cypress-multi-reporters",
  "reporterOptions": {
    "configFile": "reporterOpts.json"
  }
```

See https://github.com/YOU54F/cypress-docker-typescript/pull/22/files

**Comment by francisu** [comment]
1.5.1 now supports the current version of mocha
