### ISSUE TITLE
Cannot load mochawesome reporter

### ISSUE THREAD

**Issue by ChrisSquare** [stanleyhlng/mocha-multi-reporters#62]
### Expected behavior
Should work when using mochawesome reporter in mocha configuration
### Actual behavior
```
"mochawesome" reporter not found
Reporter does not found! mochawesome
temp/node_modules/.registry.npmjs.org/mocha-multi-reporters/1.1.7/node_modules/mocha-multi-reporters/lib/MultiReporters.js:91
        return typeof reporter.done === 'function';
                               ^

TypeError: Cannot read property 'done' of undefined
    at temp/node_modules/.registry.npmjs.org/mocha-multi-reporters/1.1.7/node_modules/mocha-multi-reporters/lib/MultiReporters.js:91:32
```
### Information about the Issue
In mocha.opts using
```
--reporter mocha-multi-reporters
--reporter-options configFile=test/mocha_reporter_config.json
```
with `"reporterEnabled": "xunit,mochawesome"` in _mocha_reporter_config.json_
The error does not provide more info on why the mochawesome reporter failed to be loaded:
https://github.com/stanleyhlng/mocha-multi-reporters/blob/807dfa10c82d29f057abf5960bb0e36d8b69f41b/lib/MultiReporters.js#L53
### Steps to reproduce the behavior
Couldn't reproduce it, but my colleagues do and it's mostly a local issue. We're using `rush` so maybe there's a dependency issue between `mochawesome` and `mocha-multi-reporters`.

**Comment by YOU54F** [comment]
this fix may help

https://github.com/stanleyhlng/mocha-multi-reporters/pull/61

**Comment by francisu** [comment]
The suggested fix has been merged. If this is still an issue, can you reopen?
