### ISSUE TITLE
Cannot add config with multi reporters (mochawesome and mocha-junit-reporter)

### ISSUE THREAD

**Issue by jackmercy** [stanleyhlng/mocha-multi-reporters#64]
### Expected behavior
I have tried export multiple reports that have HTML (from `mochawesome` and `mochawesome-report-generator`) and XML file from `mocha-junit-reporter`.
But getting error with the config.
But when I 
### Actual behavior
When I use each one of them individually, the config work perfectly.
When I tried using multi reporter with this config, It works fine (config below)
```
"reporter": "mocha-multi-reporters",
"reporterOptions": {
        "reporterEnabled": "mochawesome, mocha-junit-reporter"    
    }
```

But when I tried to add custom report directory or some config. I'm getting error about that config even it works when I'm using the reporter stand alone.
### Information about the Issue
Attempt 1: This config gives me an error : `Cannot set property 'mochaFile' of undefined`
```
"reporter": "mocha-multi-reporters",
    "reporterOptions": {
        "reporterEnabled": "mocha-junit-reporter",
        "mochaJunitReporterReporterOptions": {
            "mochaFile": "junit-custom.xml"
        }
    }
```
Attempt 2: This config gives me error: `Cannot set property 'reportDir' of undefined`
```
"reporter": "mochawesome",
    "reporterOptions": {
        "reporterEnabled": "mochawesome",
        "reportDir": "cypress/reports/results",
        "overwrite": false,
        "html": false,
        "json": true
    }
```
Attempt 3: This config gives me error: `Cannot set property 'reportDir' of undefined`
```
"reporter": "mocha-multi-reporters",
    "reporterOptions": {
        "reporterEnabled": "mochawesome, mocha-junit-reporter",
        "mochawesomeReporterOptions": {
           "reportDir": "cypress/reports/results",
             "overwrite": false,
            "html": false,
             "json": true,
        }
    }
```

Attempt 4: This config gives me error:  `Cannot set property 'reportDir' of undefined`
```
"reporter": "mocha-multi-reporters",
    "reporterOptions": {
        "reporterEnabled": "mochawesome, mocha-junit-reporter",
        "reportDir": "cypress/reports/results",
        "overwrite": false,
        "html": false,
        "json": true,
        "mochaJunitReporterReporterOptions": {
            "mochaFile": "cypress/reports/junit-custom.xml"
        }
    }
```

**Comment by jackmercy** [comment]
Turn out, I put the config inside environment folder config will not make it work. 
I have to put in the cypress.json
I have multiple environments config for each env.  I want dev env will only have html report, QA will have XML and HTML. 
But seem like I have to put reporter config in the cypress.json in other to make it work.
I will close issue but hopefully someday you guys will make the config can be read from env folder of cypress.

**Comment by dragon788** [comment]
Looks like this fork has a way to potentially do it through additional config options without hardcoding them in the cypress.json.

https://github.com/you54f/cypress-multi-reporters#cmroutput-option
